name: Multi-Account Testing

on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  dev_check:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      environment: dev # must match environment namespace created in GitHub

  prod_check:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      environment: prod # must match environment namespace created in GitHub


