name: Multi-Account Testing

on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
  # Dev is 1111111, Prod is 2222222

jobs:
  dev_check:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "getting account number via env ${{ env.ACCOUNT_NUMBER }}"
      - run: |
          if [ "${{ env.ACCOUNT_NUMBER }}" = "111111" ]; then
            echo "env.ACCOUNT_NUMBER is equal to 111111"
          fi
      - run: echo "getting account number directly via secrets ${{ secrets.ACCOUNT_NUMBER }}"
      - run: |
          if [ "${{ secrets.ACCOUNT_NUMBER }}" = "111111" ]; then
            echo "secrets.ACCOUNT_NUMBER is equal to 111111"
          fi
      - run: echo "getting random variable ${{ vars.VARIABLE }}"
      

  prod_check:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "getting account number via env ${{ env.ACCOUNT_NUMBER }}"
      - run: |
          if [ "${{ env.ACCOUNT_NUMBER }}" = "222222" ]; then
            echo "env.ACCOUNT_NUMBER is equal to 222222"
          fi
      - run: echo "getting account number directly via secrets ${{ secrets.ACCOUNT_NUMBER }}"
      - run: |
          if [ "${{ secrets.ACCOUNT_NUMBER }}" = "222222" ]; then
            echo "secrets.ACCOUNT_NUMBER is equal to 222222"
          fi
      - run: echo "getting random variable ${{ vars.VARIABLE }}"
      

